### ISSUE TITLE
epOut returns None

### ISSUE THREAD

**Issue by nicholaspearson** [jpyth/seneye-python#1]
Hi,

I've tried using your code to get my Seneye working via the Python script on a RPi.

`pi@raspberrypi:~ $ python test.py
('device       >>>', <DEVICE ID 24f7:2201 on Bus 001 Address 004>)
('configuration>>>', <CONFIGURATION 1: 100 mA>)
('interface    >>>', <INTERFACE 0: Human Interface Device>)
Traceback (most recent call last):
  File "test.py", line 169, in <module>
    main()
  File "test.py", line 154, in main
    dev,epIn,epOut,interface = set_up()
  File "test.py", line 47, in set_up
    assert epOut is not None
AssertionError`

The above is the response I get, I've checked the Vendor/product is correct.

Please could you help?

**Comment by devclef** [comment]
I don't know if it could be the cause.. but the configuration is only 100mA.. mine shows 250mA. 

Is this a full size raspberrypi or any chance the USB is under powered? 

Here is what my setup looks like. 
root@raspberrypi:/home/dopey# python bin/seneye-pi.py 
('device       >>>', <DEVICE ID 24f7:2204 on Bus 001 Address 007>)
('configuration>>>', <CONFIGURATION 1: 250 mA>)
('interface    >>>', <INTERFACE 0: Human Interface Device>)
('endpoint in  >>>', <ENDPOINT 0x81: Interrupt IN>)
('endpoint out >>>', <ENDPOINT 0x1: Interrupt OUT>)

What's the output of lsusb -v ?
